=== EvansRigopoulos/MDP/studentList.dtd
<!ELEMENT studentList (student*, highaverage*)> 
<!ELEMENT student (name, lastname, lessons, avg,semester)> 
<!ELEMENT name (#PCDATA)> 
<!ELEMENT lastname (#PCDATA)> 
<!ELEMENT lessons (#PCDATA)> 
<!ELEMENT avg (#PCDATA)> 
<!ELEMENT semester (#PCDATA)> 

<!ELEMENT highaverage (Sname, Slastname, Slessons,Savg)> 
<!ELEMENT Sname (#PCDATA)> 
<!ELEMENT Slastname (#PCDATA)> 
<!ELEMENT Slessons (#PCDATA)>
<!ELEMENT Savg (#PCDATA)>

=== EvansRigopoulos/MDP/studentList3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentList SYSTEM "studentList.dtd">
<studentList>
  <student>
    <name>Δημήτρης </name>
    <lastname>Δημητρίου</lastname>
    <lessons>7</lessons>
    <avg>7.0000</avg>
    <semester>3</semester>
  </student>
  <student>
    <name>Ηλίας </name>
    <lastname>Ηλίου</lastname>
    <lessons>7</lessons>
    <avg>7.0000</avg>
    <semester>3</semester>
  </student>
  <highaverage>
    <Sname>Ηλίας </Sname>
    <Slastname>Ηλίου</Slastname>
    <Slessons>7</Slessons>
    <Savg>7.0000</Savg>
  </highaverage>
  <highaverage>
    <Sname>Δημήτρης </Sname>
    <Slastname>Δημητρίου</Slastname>
    <Slessons>7</Slessons>
    <Savg>7.0000</Savg>
  </highaverage>
</studentList>

=== EvansRigopoulos/MDP/studentList1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentList SYSTEM "studentList.dtd">
<studentList>
  <student>
    <name>Βασίλης </name>
    <lastname>Βασιλείου</lastname>
    <lessons>1</lessons>
    <avg>5.0000</avg>
    <semester>1</semester>
  </student>
  <highaverage>
    <Sname>Βασίλης </Sname>
    <Slastname>Βασιλείου</Slastname>
    <Slessons>1</Slessons>
    <Savg>5.0000</Savg>
  </highaverage>
</studentList>

=== EvansRigopoulos/MDP/studentList2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentList SYSTEM "studentList.dtd">
<studentList>
  <student>
    <name>Άγγελος</name>
    <lastname>Αγγέλου</lastname>
    <lessons>2</lessons>
    <avg>6.5000</avg>
    <semester>2</semester>
  </student>
  <student>
    <name>Γιώργος </name>
    <lastname>Γεωργίου</lastname>
    <lessons>3</lessons>
    <avg>6.3333</avg>
    <semester>2</semester>
  </student>
  <student>
    <name>Ευάγγελος</name>
    <lastname>Ρηγόπουλος</lastname>
    <lessons>3</lessons>
    <avg>8.6667</avg>
    <semester>2</semester>
  </student>
  <highaverage>
    <Sname>Ευάγγελος</Sname>
    <Slastname>Ρηγόπουλος</Slastname>
    <Slessons>3</Slessons>
    <Savg>8.6667</Savg>
  </highaverage>
  <highaverage>
    <Sname>Άγγελος</Sname>
    <Slastname>Αγγέλου</Slastname>
    <Slessons>2</Slessons>
    <Savg>6.5000</Savg>
  </highaverage>
</studentList>
